
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: harbor-cert
  namespace: harbor
spec:
  dnsNames:
    - harbor.demo.potomacempire.com
  secretName: harbor-tls
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-cert
  namespace: argocd
spec:
  dnsNames:
    - argocd.demo.potomacempire.com
  secretName: argocd-tls
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-cert
  namespace: keycloak
spec:
  dnsNames:
    - keycloak.demo.potomacempire.com
  secretName: keycloak-tls
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer